### ISSUE TITLE
How to Quantize with SpinQuant and Export to VLLM

### ISSUE THREAD

**Issue by TweedBeetle** [ModelTC/llmc#175]
Hello LLMC Team,

I am using **SpinQuant** with **LLMC** to quantize a LLaMA model and would like to export the quantized model for deployment with **VLLM**. However, I'm unsure about the exact configuration settings required to ensure compatibility.

### **Current Configuration:**

```yaml
{
    "base": {
        "seed": 9592
    },
    "model": {
        "type": model_type,
        "path": base_model_path,
        "torch_dtype": "auto"
    },
    "quant": {
        "method": "SpinQuant",
        "weight": {
            "bit": 4,
            "symmetric": False,
            "granularity": "per_channel",
            "group_size": -1,
            "qmax_to_tensor": True,
            "calib_algo": "mse",
            "ste": True
        },
        "act": {
            "bit": 4,
            "symmetric": False,
            "granularity": "per_token",
            "qmax_to_tensor": True,
            "ste": True
        },
        "special": {
            "rotate_mode": "hadamard",
            "fp32_had": True,
            "online_rotate": True
        }
    },
    "save": {
        "save_vllm": True,
        "save_trans": False,
        "save_fake": False,
        "save_sgl": False,
        "save_autoawq": False,
        "save_mlcllm": False,
        "save_path": output_dir,
    }
}
```

What additional configuration is needed to export the SpinQuant-quantized model in a format compatible with VLLM?

Currently, the specified output folder remains empty.

Any help appreciated!
