### ISSUE TITLE
why llmc do not support asymmetric quantization?

### ISSUE THREAD

**Issue by hensiesp32** [ModelTC/llmc#258]
Hi, thanks for your wonderful work. I wonder why llmc's quantization doesn't support asymmetric quantization if i set `save_vllm = True`
The config is as below:
```
base:
    seed: &seed 42
model:
    type: Qwen2
    path: /mnt/public/lingo-engine/model_info/multidoc_masterthemev11_qwen2_7b_bf16_240904
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /mnt/public/lingo-engine/data/pileval_dataset/
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: general
    seed: *seed
quant:
    method: Awq
    weight:
        bit: 8
        **symmetric: False**
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        **symmetric: False**
        granularity: per_token
    special:
        trans: True
        trans_version: v2
        weight_clip: True
    quant_out: True
save:
    save_vllm: True
    save_path: /mnt/public/daixin/masterthemev11_qwen2_7b_awq_w8a8_unsym
```
Then I get error:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 317, in <module>
[rank0]:     main(config)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 194, in main
[rank0]:     assert w.symmetric, 'Only symmetric quant is supported.'
```
https://github.com/ModelTC/llmc/blob/5e3361ce7afa87e62a82afb0acd4487cced8ab63/llmc/__main__.py#L194
