### ISSUE TITLE
fail to run awq+ominiq on Qwen2-7b

### ISSUE THREAD

**Issue by hensiesp32** [ModelTC/llmc#280]
Hi, I was trying to test W4A16 with awq+ominiq, however there was an error with ominiq.
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 317, in <module>
[rank0]:     main(config)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 121, in main
[rank0]:     blockwise_opt.run_block_loop()
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/blockwise_optimization.py", line 40, in run_block_loop
[rank0]:     self.block_opt(self.blocks[self.block_idx])
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/base_blockwise_quantization.py", line 418, in block_opt
[rank0]:     self.run(block, input_feat, handles)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/base_blockwise_quantization.py", line 449, in run
[rank0]:     self.block_transform(block, input_feat, self.input['kwargs'])
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 166, in block_transform
[rank0]:     self.register_omni_parameters(block, input_feat)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 286, in register_omni_parameters
[rank0]:     self.register_lwc_parameters(block, input_feat)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 294, in register_lwc_parameters
[rank0]:     low_param, up_param = self.get_clip_parameters(input_feat, n, m)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 389, in get_clip_parameters
[rank0]:     max_val, min_val = self.auto_clipper.auto_clip_layer(
[rank0]: AttributeError: 'OmniQuant' object has no attribute 'auto_clipper'
```

The config was following:
awq
```
base:
    seed: &seed 42
model:
    type: Qwen2
    path: /mnt/public/lingo-engine/model_info/multidoc_masterthemev11_qwen2_7b_bf16_240904
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /mnt/public/lingo-engine/data/pileval_dataset/
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: general
    seed: *seed
# eval:
#     eval_pos: [fake_quant]
#     name: wikitext2
#     download: False
#     path: eval data path
#     seq_len: 2048
#     # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
#     # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
#     bs: 1
#     inference_per_block: False
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        calib_algo: minmax
    special:
        trans: True
        trans_version: v2
        weight_clip: False
        # For weight-only AWQ+Omni mode, there's no need to save scale factors;
        # Only the AWQ-transformed model needs to be saved.
        save_scale: False
        save_clip: False
save:
    # Save the AWQ-transformed model.
    save_trans: True
    save_path: /mnt/public/daixin/masterthemev11_qwen2_7b_awq_w4_fake
```
ominiq
```
base:
    seed: &seed 42
model:
    type: Qwen2
    # Load AWQ-transformed model
    path: /mnt/public/daixin/masterthemev11_qwen2_7b_awq_w4_fake/transformed_model
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /mnt/public/lingo-engine/data/pileval_dataset/
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: general
    seed: *seed
# eval:
#     eval_pos: [fake_quant]
#     name: wikitext2
#     download: False
#     path: eval data path
#     seq_len: 2048
#     # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
#     # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
#     bs: 1
#     inference_per_block: False
quant:
    method: OmniQuant
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        calib_algo: learnable
        ste: True
        need_pack: True
    special:
        aug_loss: False
        lwc: True
        let: False
        lwc_lr: 0.01
        let_lr: 0.005
        use_shift: False
        alpha: 0.5
        deactive_amp: True
        epochs: 5
        wd: 0
        # Use AWQ's search clip factors to initialize OmniQuant's clip factors,
        # Then refine them through learning (LWC).
        # Only the version v2 clipping method supports LWC.
        # This process is automatically handled in OmniQuant's code.
        search_clip_init: True
    quant_out: True
save:
    save_vllm: True
    save_path: /mnt/public/daixin/masterthemev11_qwen2_7b_awq_w4a16_awq-ominq
```
I think there was some bug in ominiq, could you help me to have a look why?

**Comment by hensiesp32** [comment]
I'm afraid that the awq configuration file you give，the `weight_clip: False` must be `True` can Ominiq execute smoothly. Am i right?

**Comment by gushiqiao** [comment]
Please use the latest llmc code, it's fixed

**Comment by hensiesp32** [comment]
However, after update, the latest llmc code doesn't support Qwen2 model with awq?
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 257, in <module>
[rank0]:     main(config)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 82, in main
[rank0]:     blockwise_opt.run_block_loop()
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/blockwise_optimization.py", line 38, in run_block_loop
[rank0]:     self.block_opt(self.blocks[self.block_idx])
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/base_blockwise_quantization.py", line 427, in block_opt
[rank0]:     self.run(block, input_feat, handles)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/base_blockwise_quantization.py", line 458, in run
[rank0]:     self.block_transform(block, input_feat, self.input['kwargs'])
[rank0]:   File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/awq.py", line 257, in block_transform
[rank0]:     super().block_transform(block, input_feat, block_kwargs)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/base_blockwise_quantization.py", line 498, in block_transform
[rank0]:     self.subset_transform(
[rank0]:   File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/awq.py", line 339, in subset_transform
[rank0]:     scale = self.search_scale_subset(
[rank0]:   File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/awq.py", line 164, in search_scale_subset
[rank0]:     scales = self.get_scales(prev_op, x, w_max, is_gqa, ratio)
[rank0]:   File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/awq.py", line 85, in get_scales
[rank0]:     (x_tmp.pow(ratio) / w_tmp.pow(1 - ratio))
[rank0]: RuntimeError: The size of tensor a (512) must match the size of tensor b (3584) at non-singleton dimension 0
``` 
I was running Qwen2 with awq，the config is following:
```
base:
    seed: &seed 42
model:
    type: Qwen2
    path: /mnt/public/lingo-engine/model_info/multidoc_masterthemev11_qwen2_7b_bf16_240904
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /mnt/public/lingo-engine/data/pileval_dataset
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        calib_algo: minmax
    special:
        trans: True
        trans_version: v1
        weight_clip: False
        # For weight-only AWQ+Omni mode, there's no need to save scale factors;
        # Only the AWQ-transformed model needs to be saved.
        save_scale: False
        save_clip: False
save:
    # Save the AWQ-transformed model.
    save_trans: True
    save_path: /mnt/public/daixin/masterthemev11_qwen2_7b_awq_w4_fake
```

**Comment by gushiqiao** [comment]
Please try trans_version: v1->v2. Additionally, it is preferable to set 'bs' to -1, as this can result in faster and more accurate processing compared to using bs=1.

**Comment by hensiesp32** [comment]
Does it mean that for the GQA model, the trans_version = v1 of AWQ has already been deprecated?

**Comment by gushiqiao** [comment]
Yeah, but I just got it fixed. 
By the way, LLMC may be the first framework to support the GQA part to do AWQ scaling operations

**Comment by hensiesp32** [comment]
After setting trans_version = v2, it works well !Thanks for your wonderful work! LLMC helps me a lot!

**Comment by hensiesp32** [comment]
Can Ominiq support multiple GPUs? My single 4090 GPU encounters OOM issues.

**Comment by gushiqiao** [comment]
Ominiq's multi-GPU support is currently unavailable, but it is planned for future releases. 
In the meantime, you may consider utilizing a combination of gptq and quarot to ensure the accuracy of your quantization process.

**Comment by hensiesp32** [comment]
I can't run ominiq on a single gpu with 80G memory, if ominiq doesn't support multi-gpu, how can people use it? I am afraid that a single gpu-80G is almost largest devices. Or how do you use omniq?what's your device?

**Comment by gushiqiao** [comment]
How big is the model? Can you provide the config and error information?

**Comment by hensiesp32** [comment]
a Qwen2-7B model

the config file as following:
```
base:
    seed: &seed 42
model:
    type: Qwen2
    # Load AWQ-transformed model
    path: /mnt/public/daixin/masterthemev11_qwen2_7b_awq_w4_fake/transformed_model
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /mnt/public/lingo-engine/data/pileval_dataset
    n_samples: 128
    bs: -1
    seq_len: 2048
    preproc: txt_general_preproc
    seed: *seed
quant:
    method: OmniQuant
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        calib_algo: learnable
        ste: True
        need_pack: True
    special:
        aug_loss: False
        lwc: True
        let: False
        lwc_lr: 0.01
        let_lr: 0.005
        use_shift: False
        alpha: 0.5
        deactive_amp: True
        epochs: 5
        wd: 0
        # Use AWQ's search clip factors to initialize OmniQuant's clip factors,
        # Then refine them through learning (LWC).
        # Only the version v2 clipping method supports LWC.
        # This process is automatically handled in OmniQuant's code.
        search_clip_init: True
    quant_out: True
save:
    save_vllm: True
    save_path: /mnt/public/daixin/masterthemev11_qwen2_7b_vllm_awq_omni_w4/
```
the error info:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 257, in <module>
[rank0]:     main(config)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/__main__.py", line 82, in main
[rank0]:     blockwise_opt.run_block_loop()
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/blockwise_optimization.py", line 38, in run_block_loop
[rank0]:     self.block_opt(self.blocks[self.block_idx])
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/base_blockwise_quantization.py", line 427, in block_opt
[rank0]:     self.run(block, input_feat, handles)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/base_blockwise_quantization.py", line 458, in run
[rank0]:     self.block_transform(block, input_feat, self.input['kwargs'])
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 166, in block_transform
[rank0]:     self.register_omni_parameters(block, input_feat)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 286, in register_omni_parameters
[rank0]:     self.register_lwc_parameters(block, input_feat)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 294, in register_lwc_parameters
[rank0]:     low_param, up_param = self.get_clip_parameters(input_feat, n, m)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/omniq.py", line 389, in get_clip_parameters
[rank0]:     max_val, min_val = self.auto_clipper.auto_clip_layer(
[rank0]:   File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/mnt/user/daixin/llmc/llmc/compression/quantization/auto_clip.py", line 170, in auto_clip_layer
[rank0]:     cur_out = (q_x * q_w).sum(dim=-1)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 37.00 GiB. GPU 0 has a total capacity of 79.32 GiB of which 13.55 GiB is free. Process 47962 has 65.77 GiB memory in use. Of the allocated memory 27.94 GiB is allocated by PyTorch, and 37.00 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W103 10:48:35.325485699 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0103 10:48:37.262000 23088 .venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 23181) of binary: /mnt/user/daixin/llmc/.venv/bin/python
Traceback (most recent call last):
  File "/mnt/user/daixin/llmc/.venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/user/daixin/llmc/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```
