### ISSUE TITLE
Inquiry on the Implementation and Support for `vlm_datasets` Calibration Data Class

### ISSUE THREAD

**Issue by aptsunny** [ModelTC/llmc#292]
Hello,

I am currently working with the `vlm_datasets` calibration data class as outlined in the documentation [here](https://llmc-zhcn.readthedocs.io/en/latest/advanced/VLM_quant%26img-txt_dataset.html). I noticed that there seems to be some aspects of the implementation that might not be fully developed or documented.

Here are the details I've gathered from the YAML configuration:

```yaml
model:
  type: Llava
  path: model path
  tokenizer_mode: slow
  torch_dtype: auto

calib:
  name: vlm_datasets
  type: img_txt
  download: False
  path: datasets path
  n_samples: 32
  bs: 1
  seq_len: 512
  preproc: vlm_general
  padding: True
  seed: *seed
```

I have a few questions regarding the `vlm_datasets`:

1. Is the `vlm_datasets` calibration data class fully [implemented](https://github.com/ModelTC/llmc/blob/7ad5a0594521356b20c93969e494124cf72af888/llmc/data/dataset/base_dataset.py#L77) and supported?
2. Are there any known limitations or issues with the current implementation?
3. If it's not fully implemented, is there a timeline for when these features might be completed?

I would appreciate any guidance or clarification on this matter. If there is additional documentation or resources available, please let me know.

Thank you for your time and support.

Best regards
